// Generated by CoffeeScript 1.7.1
(function() {
  var $event, map;

  map = {};

  this.coordinates = {};

  this.googlemaps = function() {
    console.log('hello');
    navigator.geolocation.getCurrentPosition((function(_this) {
      return function(data) {
        var mapOptions, marker;
        _this.coordinates = data.coords;
        console.log("Accuracy: " + _this.coordinates.accuracy, "Altitude: " + _this.coordinates.altitude, "Altitude Accuracy: " + _this.coordinates.altitudeAccuracy, "Heading: " + _this.coordinates.heading, "Latitude: " + _this.coordinates.latitude, "Longitude: " + _this.coordinates.longitude, "Speed: " + _this.coordinates.speed);
        _this.myLatlng = new google.maps.LatLng(_this.coordinates.latitude, _this.coordinates.longitude);
        mapOptions = {
          center: _this.myLatlng,
          zoom: 13,
          styles: _this.Midnight_Commander
        };
        map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
        return marker = new google.maps.Marker({
          position: _this.myLatlng,
          animation: google.maps.Animation.DROP,
          map: map
        });
      };
    })(this));
    return google.maps.event.addDomListener(window, "resize", function() {
      var center;
      center = map.getCenter();
      google.maps.event.trigger(map, "resize");
      return map.setCenter(this.myLatlng);
    });
  };

  $(document).ready((function(_this) {
    return function() {
      return _this.googlemaps();
    };
  })(this));

  $('.testbtn').click((function(_this) {
    return function() {
      var contentString, infowindow, marker;
      contentString = '<div id="content">' + '<div id="siteNotice">' + '</div>' + '<h1 id="firstHeading" class="firstHeading">Test Player</h1>' + '<div id="bodyContent">' + '<p>Test Content </p>' + '</div>' + '</div>';
      infowindow = new google.maps.InfoWindow({
        content: contentString
      });
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(_this.coordinates.latitude - 0.01, _this.coordinates.longitude - 0.01),
        animation: google.maps.Animation.DROP,
        map: map,
        title: "Test Player"
      });
      return google.maps.event.addListener(marker, "click", function() {
        console.log(marker);
        return infowindow.open(map, marker);
      });
    };
  })(this));

  this.msg = {
    'message': 'test'
  };

  $event = $('.event');

  $event.click(function() {
    return channel.trigger('client-geo', coordinates);
  });

}).call(this);

//# sourceMappingURL=app.map
