// Generated by CoffeeScript 1.7.1
(function() {
  var $body, $el, $menuButton, $menuLeft, $menuRight, i, map, socket;

  map = {};

  this.coordinates = {};

  this.user = {};

  navigator.geolocation.getCurrentPosition((function(_this) {
    return function(data) {
      var userId;
      _this.coordinates = data.coords;
      console.log("Accuracy: " + _this.coordinates.accuracy, "Altitude: " + _this.coordinates.altitude, "Altitude Accuracy: " + _this.coordinates.altitudeAccuracy, "Heading: " + _this.coordinates.heading, "Latitude: " + _this.coordinates.latitude, "Longitude: " + _this.coordinates.longitude, "Speed: " + _this.coordinates.speed);
      userId = 12;
      _this.user = {
        userId: userId,
        userName: "webUser",
        lon: _this.coordinates.longitude,
        lat: _this.coordinates.latitude
      };
      console.log("user", _this.user);
      return socket.emit('init', _this.user);
    };
  })(this));

  this.googlemaps = function() {
    console.log('hello');
    return navigator.geolocation.getCurrentPosition((function(_this) {
      return function(data) {
        var mapOptions, marker;
        _this.coordinates = data.coords;
        console.log("Accuracy: " + _this.coordinates.accuracy, "Altitude: " + _this.coordinates.altitude, "Altitude Accuracy: " + _this.coordinates.altitudeAccuracy, "Heading: " + _this.coordinates.heading, "Latitude: " + _this.coordinates.latitude, "Longitude: " + _this.coordinates.longitude, "Speed: " + _this.coordinates.speed);
        _this.myLatlng = new google.maps.LatLng(_this.coordinates.latitude, _this.coordinates.longitude);
        mapOptions = {
          center: _this.myLatlng,
          zoom: 13,
          styles: _this.Midnight_Commander
        };
        map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
        return marker = new google.maps.Marker({
          position: _this.myLatlng,
          animation: google.maps.Animation.DROP,
          map: map
        });
      };
    })(this));
  };

  google.maps.event.addDomListener(window, "resize", function() {
    var center;
    center = map.getCenter();
    google.maps.event.trigger(map, "resize");
    return map.setCenter(this.myLatlng);
  });

  $(document).ready((function(_this) {
    return function() {
      return _this.googlemaps();
    };
  })(this));

  $('.testbtn').click(function() {
    var contentString, infowindow, marker;
    contentString = '<div id="content">' + '<div id="siteNotice">' + '</div>' + '<h1 id="firstHeading" class="firstHeading">Test Player</h1>' + '<div id="bodyContent">' + '<p>Test Content </p>' + '</div>' + '</div>';
    infowindow = new google.maps.InfoWindow({
      content: contentString
    });
    marker = new google.maps.Marker({
      position: new google.maps.LatLng(coordinates.latitude - 0.01, coordinates.longitude - 0.01),
      animation: google.maps.Animation.DROP,
      map: map,
      title: "Test Player"
    });
    return google.maps.event.addListener(marker, "click", function() {
      console.log(marker);
      return infowindow.open(map, marker);
    });
  });


  /*
    Socket.io
   */

  socket = io.connect('107.170.141.208');

  socket.emit("update", user);

  socket.on('newUser', function(data) {
    var latlng;
    console.log('NewUser', data);
    console.log(data.lat, data.lon);
    latlng = new google.maps.LatLng(data.lat, data.lon);
    return this.player2 = new google.maps.Marker({
      position: latlng,
      map: map
    });
  });

  $('#msg').keypress(function(e) {
    if (e.which === 13) {
      socket.emit('chat', {
        userName: 'webUser',
        msg: $('#msg').val()
      });
      $('#msg').val('');
      return $('#chat p').last().focus();
    }
  });

  socket.on('chat', function(data) {
    console.log("chat", data);
    return $('#chat').append($('<p>', {
      text: data.msg
    }));
  });

  $('#update').click(function() {
    var marker;
    console.log(user);
    socket.emit('update', user);
    return marker = new google.maps.Marker({
      position: new google.maps.LatLng(coordinates.latitude - 0.01, coordinates.longitude - 0.01),
      animation: google.maps.Animation.DROP,
      map: map
    });
  });

  socket.on('update', function(data) {
    var marker;
    console.log('update', data);
    console.log(data.lat, data.lon);
    return marker = new google.maps.Marker({
      position: new google.maps.LatLng(coordinates.latitude, coordinates.longitude),
      animation: google.maps.Animation.DROP,
      map: map
    });
  });

  i = 0;

  socket.on('init', function(data) {
    var latlng, users, _results;
    users = data;
    _results = [];
    while (i < users.length) {
      users[i];
      users[i].location[0].lat;
      users[i].location[0].lon;
      console.log(users[i].location[0].lat, users[i].location[0].lon);
      latlng = new google.maps.LatLng(users[i].location[0].lat, users[i].location[0].lon);
      users[i].userId = new google.maps.Marker({
        position: latlng,
        animation: google.maps.Animation.DROP
      });
      users[i].userId.setMap(map);
      _results.push(i++);
    }
    return _results;
  });

  $menuButton = $('.navbar-toggle');

  $menuLeft = $('.menu-left');

  $menuRight = $('.menu-right');

  $body = $('body');

  $el = $(this);

  $menuButton.click(function() {
    $el.toggleClass("active");
    $body.toggleClass(" menu-push-toleft");
    $('#overlay').toggleClass("overlay");
    return $menuRight.toggleClass("menu-open");
  });

  $('#overlay').click(function() {
    $menuButton.removeClass("active");
    $body.removeClass("menu-push-toleft");
    $body.removeClass("menu-push-toright");
    $menuRight.removeClass("menu-open");
    $menuLeft.removeClass("menu-open");
    $('#overlay').removeClass("overlay");
    return $('.navbar-toggle').removeClass('disabled');
  });

}).call(this);

//# sourceMappingURL=app.map
